CREATE DATABASE PurBeurreDb;

CREATE TABLE categories(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(250) UNIQUE NOT NULL
)
ENGINE = INNODB;


CREATE TABLE foods(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(250) UNIQUE NOT NULL, 
    nova_group TINYINT NOT NULL,
    category_id INT UNSIGNED NOT NULL,
    off_url VARCHAR(250)
)
ENGINE = INNODB;

ALTER TABLE foods
ADD FOREIGN KEY (category_id) REFERENCES categories(id);


CREATE TABLE favorites(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    foods_subs_id INT UNSIGNED UNIQUE NOT NULL,
    foods_id INT UNSIGNED UNIQUE NOT NULL
)
ENGINE = INNODB;

ALTER TABLE favorites
ADD FOREIGN KEY (foods_subs_id) REFERENCES foods(id),
ADD FOREIGN KEY (foods_id) REFERENCES foods(id);


CREATE TABLE stores(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    stores_name VARCHAR(250) UNIQUE
)
ENGINE = INNODB;


CREATE TABLE foods_stores(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    foods_id INT UNSIGNED NULL,
    stores_id INT UNSIGNED NULL
)
ENGINE = INNODB;

ALTER TABLE foods_stores
ADD FOREIGN KEY (foods_id) REFERENCES foods(id),
ADD FOREIGN KEY (stores_id) REFERENCES stores(id);






-- commandes utiles 

DROP TABLE foods_stores;
DROP TABLE stores;
DROP TABLE favorites;
DROP TABLE foods;
DROP TABLE categories;




SELECT * FROM foods;
SELECT * FROM categories;
SELECT * FROM favorites;
